### ISSUE TITLE
About Train data

### ISSUE THREAD

**Issue by huangguoqing** [andreped/PLS-Net#2]
Hello，can you provide lung lobe segmentation annotation （train data）？

**Comment by andreped** [comment]
Hello, the lobe segmentation results that was displayed in the README, was produced in a Master's thesis (see [here](https://ntnuopen.ntnu.no/ntnu-xmlui/handle/11250/2778113) or click [here](https://ntnuopen.ntnu.no/ntnu-xmlui/bitstream/handle/11250/2778113/no.ntnu%3ainspera%3a53184405%3a45291869.pdf?sequence=1&isAllowed=y) to download PDF directly). To the best of my knowledge, this dataset is not openly available.

However, `Wasserthal et al.` have released **1204 annotated CTs** on Zenodo which **include lung lobe segmentations** (see [here](https://zenodo.org/record/6802614#.ZCFLd-xBwTs)).

If you just need a model for deployment, you could also download the [TotalSegmentor tool](https://github.com/wasserth/TotalSegmentator) which has a permissive license, and then you don't need to train a model yourself.

**Comment by huangguoqing** [comment]
Thanks for your answer,I see it

**Comment by andreped** [comment]
Closing for now. Please, let me know if you are experiencing any other issues. Good luck on your future endeavours! :]
